### ISSUE TITLE
How many mutations does an MNP count as?

### ISSUE THREAD

**Issue by tnguyensanger** [phe-genomics/variant_definitions#15]
Should an MNP count as a single mutation?  Or should it count as the total contiguous SNPs covered by the MNP?

In the omicron definition v0.6.1: https://github.com/phe-genomics/variant_definitions/blob/0.6.1/variant_yaml/pentagon-refining.yml

The definition contains 25 SNPs, 4 deletions, and 1 MNP.  However, for a confirmed result, requires 27 mutations, 0 indels.  If the MNP counts as a single mutation, then we can only ever call a sample as 'probable' if we ignore deletions.

Does the ````mutations-required```` count include deletions?

````
calling-definition:
  confirmed:
    mutations-required: 27
    indels-required: 0
    allowed-wildtype: 0
````
